#include "cfd/core/BuildInfo.hpp"

#include <format>

#include "cfd/core/Version.hpp"  // generated by CMake into build/generated

// These come from target_compile_definitions in src/core/CMakeLists.txt.
// Defaults keep the file compilable if it is ever built outside our CMake
// setup (e.g. by a standalone analysis tool).
#ifndef CFD_BUILD_TYPE
#define CFD_BUILD_TYPE "Unknown"
#endif
#ifndef CFD_COMPILER_ID
#define CFD_COMPILER_ID "Unknown"
#endif
#ifndef CFD_COMPILER_VERSION
#define CFD_COMPILER_VERSION "0"
#endif

namespace cfd {
namespace {

/// __cplusplus is the standard the compiler actually applied to this file,
/// which is more trustworthy than repeating CMAKE_CXX_STANDARD by hand.
constexpr std::string_view cxxStandardName() noexcept {
#if __cplusplus >= 202302L
  return "C++23";
#elif __cplusplus >= 202002L
  return "C++20";
#elif __cplusplus >= 201703L
  return "C++17";
#else
  return "pre-C++17";
#endif
}

}  // namespace

std::string_view BuildInfo::version() noexcept { return version::kString; }

std::string_view BuildInfo::projectName() noexcept { return version::kProjectName; }

std::string_view BuildInfo::description() noexcept { return version::kDescription; }

std::string_view BuildInfo::buildType() noexcept { return CFD_BUILD_TYPE; }

std::string_view BuildInfo::compiler() noexcept {
  // Adjacent string literals are concatenated at compile time, so this is a
  // view over static storage and safe to return.
  return CFD_COMPILER_ID " " CFD_COMPILER_VERSION;
}

std::string_view BuildInfo::cxxStandard() noexcept { return cxxStandardName(); }

std::string BuildInfo::summary() {
  return std::format(
      "{} {}\n"
      "{}\n"
      "  build type : {}\n"
      "  compiler   : {}\n"
      "  standard   : {}\n",
      projectName(), version(), description(), buildType(), compiler(),
      cxxStandard());
}

}  // namespace cfd
